### ISSUE TITLE
Independent review of `uniffi_aries_vcx`

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#1049]
- New `uniffi_aries_vcx` component https://github.com/hyperledger/aries-vcx/tree/main/uniffi_aries_vcx has been added over the course of 2023
- It would be nice to get an independent review of the crate:
  - try to compile the uniffi wrapper
  - generate swift and kotlin bindings
  - run demo app on an android device

The output of this review shall be:
- identifying challenges going through the journey above and improving documentation, readmes, build process etc.
- possibly improvements to the code

**Comment by ivanpagac** [comment]
Hello @Patrik-Stas , 

so I am trying to prepare my env, cloned repo, executed script as per recommendations and getting 

```
➜  aries-vcx git:(main) ✗ sh uniffi_aries_vcx/scripts/android.build.cargo.ndk.sh
+++ dirname uniffi_aries_vcx/scripts/android.build.cargo.ndk.sh
++ cd uniffi_aries_vcx/scripts
++ pwd -P
+ SCRIPT_DIR=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/scripts
+++ dirname /Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/scripts
++ dirname /Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx
+ ARIES_VCX_ROOT=/Users/ivan.pagac/Projects/aries-vcx
+ ANDROID_BUILD_DEPS_DIR=/Users/ivan.pagac/Projects/aries-vcx/target/android_build_deps
+ LANGUAGE=kotlin
+ TARGET=aarch64-linux-android
+ TARGET_NICKNAME=arm64
+ ABI=arm64-v8a
+ generate_bindings
+ export UNIFFI_ROOT=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx
+ UNIFFI_ROOT=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx
+ export ANDROID_DEMO_DIR=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/demo
+ ANDROID_DEMO_DIR=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/demo
+ pushd /Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/core
~/Projects/aries-vcx/uniffi_aries_vcx/core ~/Projects/aries-vcx
+ cargo run --features=uniffi/cli --bin uniffi-bindgen generate src/vcx.udl --language kotlin
   Compiling zmq-sys v0.11.0
   Compiling libsodium-sys v0.0.16
   Compiling sqlx-mysql v0.7.2
   Compiling failure v0.1.8
   Compiling io-lifetimes v1.0.11
   Compiling reqwest v0.11.22
   Compiling rand v0.7.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling num-bigint v0.4.4
   Compiling console_error_panic_hook v0.1.7
error: failed to run custom build command for `libsodium-sys v0.0.16`

Caused by:
  process didn't exit successfully: `/Users/ivan.pagac/Projects/aries-vcx/target/debug/build/libsodium-sys-fcf7e97bdefdf8a4/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SODIUM_LIB_DIR
  cargo:rerun-if-env-changed=SODIUM_STATIC
  cargo:rerun-if-env-changed=LIBSODIUM_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBSODIUM_STATIC
  cargo:rerun-if-env-changed=LIBSODIUM_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /Users/ivan.pagac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsodium-sys-0.0.16/build.rs:20:47:
  called `Result::unwrap()` on an `Err` value: "`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"` did not exit successfully: exit status: 1\nerror: could not find system library 'libsodium' required by the 'libsodium-sys' crate\n\n--- stderr\nPackage libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libsodium.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'libsodium' found\n"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `zmq-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/Users/ivan.pagac/Projects/aries-vcx/target/debug/build/zmq-sys-e594d214ed53bc8e/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZMQ_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBZMQ_STATIC
  cargo:rerun-if-env-changed=LIBZMQ_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /Users/ivan.pagac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zmq-sys-0.11.0/build/pkg_config.rs:26:17:
  Unable to locate libzmq:
  `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "libzmq" "libzmq >= 4.1"` did not exit successfully: exit status: 1
  error: could not find system library 'libzmq' required by the 'zmq-sys' crate

  --- stderr
  Package libzmq was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libzmq.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libzmq' found
  Package libzmq was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libzmq.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libzmq' found

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

before I run the `sh uniffi_aries_vcx/scripts/android.prepare.sh ` and it end up with no issues

```
➜  aries-vcx git:(main) ✗ sh uniffi_aries_vcx/scripts/android.prepare.sh
+++ dirname uniffi_aries_vcx/scripts/android.prepare.sh
++ cd uniffi_aries_vcx/scripts
++ pwd -P
+ SCRIPT_DIR=/Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/scripts
+ ANDROID_BUILD_DIR=/Users/ivan.pagac/android_build
+ source /Users/ivan.pagac/Projects/aries-vcx/uniffi_aries_vcx/scripts/android.utils.sh
+++ tput setaf 0
++ export 'BLACK='
++ BLACK=''
+++ tput setaf 1
++ export 'RED='
++ RED=''
+++ tput setaf 2
++ export 'GREEN='
++ GREEN=''
+++ tput setaf 3
++ export 'YELLOW='
++ YELLOW=''
+++ tput setaf 4
++ export 'BLUE='
++ BLUE=''
+++ tput setaf 5
++ export 'MAGENTA='
++ MAGENTA=''
+++ tput setaf 6
++ export 'CYAN='
++ CYAN=''
+++ tput setaf 7
++ export 'WHITE='
++ WHITE=''
+++ tput bold
++ export 'BOLD='
++ BOLD=''
+++ tput sgr0
++ export 'RESET='
++ RESET=''
++ '[' -z /Users/ivan.pagac/android_build ']'
+ set_android_env
+ export PKG_CONFIG_ALLOW_CROSS=1
+ PKG_CONFIG_ALLOW_CROSS=1
+ export CARGO_INCREMENTAL=0
+ CARGO_INCREMENTAL=0
+ export RUST_LOG=indy=trace
+ RUST_LOG=indy=trace
+ export RUST_TEST_THREADS=1
+ RUST_TEST_THREADS=1
+ export RUST_BACKTRACE=1
+ RUST_BACKTRACE=1
+ export ANDROID_SDK=/Users/ivan.pagac/android_build/sdk
+ ANDROID_SDK=/Users/ivan.pagac/android_build/sdk
+ export PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools
+ PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools
+ export PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools
+ PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools
+ export PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools:/Users/ivan.pagac/android_build/sdk/tools/bin
+ PATH=/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools:/Users/ivan.pagac/android_build/sdk/tools/bin
+ export TARGET=android
+ TARGET=android
+ download_sdk
+ mkdir -p /Users/ivan.pagac/android_build/sdk
+ pushd /Users/ivan.pagac/android_build/sdk
~/android_build/sdk ~/Projects/aries-vcx
+ download_and_unzip_if_missed tools https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
+ expected_directory=tools
+ url=https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
++ date +%s
+ fname=tmp_1700485443_tools.zip
+ '[' '!' -d tools ']'
+ echo 'Downloading https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip as tmp_1700485443_tools.zip'
Downloading https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip as tmp_1700485443_tools.zip
+ wget -q -O tmp_1700485443_tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
+ echo 'Unzipping tmp_1700485443_tools.zip'
Unzipping tmp_1700485443_tools.zip
+ unzip -qqo tmp_1700485443_tools.zip
+ rm tmp_1700485443_tools.zip
+ echo 'Done!'
Done!
+ mv cmdline-tools tools
+ popd
~/Projects/aries-vcx
+ prepare_dependencies arm64
+ '[' -z arm64 ']'
+ TARGET_ARCH=arm64
+ echo 'prepare_dependencies >> TARGET_ARCH=arm64'
prepare_dependencies >> TARGET_ARCH=arm64
+ pushd /Users/ivan.pagac/android_build
~/android_build ~/Projects/aries-vcx
+ download_and_unzip_if_missed openssl_arm64 https://repo.sovrin.org/android/libindy/deps/openssl/openssl_arm64.zip
+ expected_directory=openssl_arm64
+ url=https://repo.sovrin.org/android/libindy/deps/openssl/openssl_arm64.zip
++ date +%s
+ fname=tmp_1700485499_openssl_arm64.zip
+ '[' '!' -d openssl_arm64 ']'
+ echo 'Downloading https://repo.sovrin.org/android/libindy/deps/openssl/openssl_arm64.zip as tmp_1700485499_openssl_arm64.zip'
Downloading https://repo.sovrin.org/android/libindy/deps/openssl/openssl_arm64.zip as tmp_1700485499_openssl_arm64.zip
+ wget -q -O tmp_1700485499_openssl_arm64.zip https://repo.sovrin.org/android/libindy/deps/openssl/openssl_arm64.zip
+ echo 'Unzipping tmp_1700485499_openssl_arm64.zip'
Unzipping tmp_1700485499_openssl_arm64.zip
+ unzip -qqo tmp_1700485499_openssl_arm64.zip
+ rm tmp_1700485499_openssl_arm64.zip
+ echo 'Done!'
Done!
+ download_and_unzip_if_missed libsodium_arm64 https://repo.sovrin.org/android/libindy/deps/sodium/libsodium_arm64.zip
+ expected_directory=libsodium_arm64
+ url=https://repo.sovrin.org/android/libindy/deps/sodium/libsodium_arm64.zip
++ date +%s
+ fname=tmp_1700485502_libsodium_arm64.zip
+ '[' '!' -d libsodium_arm64 ']'
+ echo 'Downloading https://repo.sovrin.org/android/libindy/deps/sodium/libsodium_arm64.zip as tmp_1700485502_libsodium_arm64.zip'
Downloading https://repo.sovrin.org/android/libindy/deps/sodium/libsodium_arm64.zip as tmp_1700485502_libsodium_arm64.zip
+ wget -q -O tmp_1700485502_libsodium_arm64.zip https://repo.sovrin.org/android/libindy/deps/sodium/libsodium_arm64.zip
+ echo 'Unzipping tmp_1700485502_libsodium_arm64.zip'
Unzipping tmp_1700485502_libsodium_arm64.zip
+ unzip -qqo tmp_1700485502_libsodium_arm64.zip
+ rm tmp_1700485502_libsodium_arm64.zip
+ echo 'Done!'
Done!
+ download_and_unzip_if_missed libzmq_arm64 https://repo.sovrin.org/android/libindy/deps/zmq/libzmq_arm64.zip
+ expected_directory=libzmq_arm64
+ url=https://repo.sovrin.org/android/libindy/deps/zmq/libzmq_arm64.zip
++ date +%s
+ fname=tmp_1700485504_libzmq_arm64.zip
+ '[' '!' -d libzmq_arm64 ']'
+ echo 'Downloading https://repo.sovrin.org/android/libindy/deps/zmq/libzmq_arm64.zip as tmp_1700485504_libzmq_arm64.zip'
Downloading https://repo.sovrin.org/android/libindy/deps/zmq/libzmq_arm64.zip as tmp_1700485504_libzmq_arm64.zip
+ wget -q -O tmp_1700485504_libzmq_arm64.zip https://repo.sovrin.org/android/libindy/deps/zmq/libzmq_arm64.zip
+ echo 'Unzipping tmp_1700485504_libzmq_arm64.zip'
Unzipping tmp_1700485504_libzmq_arm64.zip
+ unzip -qqo tmp_1700485504_libzmq_arm64.zip
+ rm tmp_1700485504_libzmq_arm64.zip
+ echo 'Done!'
Done!
+ popd
~/Projects/aries-vcx
+ set_dependencies_env_vars
+ export OPENSSL_DIR=/Users/ivan.pagac/android_build/openssl_arm64
+ OPENSSL_DIR=/Users/ivan.pagac/android_build/openssl_arm64
+ export SODIUM_DIR=/Users/ivan.pagac/android_build/libsodium_arm64
+ SODIUM_DIR=/Users/ivan.pagac/android_build/libsodium_arm64
+ export LIBZMQ_DIR=/Users/ivan.pagac/android_build/libzmq_arm64
+ LIBZMQ_DIR=/Users/ivan.pagac/android_build/libzmq_arm64
+ export SODIUM_LIB_DIR=/Users/ivan.pagac/android_build/libsodium_arm64/lib
+ SODIUM_LIB_DIR=/Users/ivan.pagac/android_build/libsodium_arm64/lib
+ export SODIUM_INCLUDE_DIR=/Users/ivan.pagac/android_build/libsodium_arm64/include
+ SODIUM_INCLUDE_DIR=/Users/ivan.pagac/android_build/libsodium_arm64/include
+ export SODIUM_STATIC=1
+ SODIUM_STATIC=1
+ export LIBZMQ_LIB_DIR=/Users/ivan.pagac/android_build/libzmq_arm64/lib
+ LIBZMQ_LIB_DIR=/Users/ivan.pagac/android_build/libzmq_arm64/lib
+ export LIBZMQ_INCLUDE_DIR=/Users/ivan.pagac/android_build/libzmq_arm64/include
+ LIBZMQ_INCLUDE_DIR=/Users/ivan.pagac/android_build/libzmq_arm64/include
+ export LIBZMQ_PREFIX=/Users/ivan.pagac/android_build/libzmq_arm64
+ LIBZMQ_PREFIX=/Users/ivan.pagac/android_build/libzmq_arm64
+ export OPENSSL_LIB_DIR=/Users/ivan.pagac/android_build/openssl_arm64/lib
+ OPENSSL_LIB_DIR=/Users/ivan.pagac/android_build/openssl_arm64/lib
+ export OPENSSL_STATIC=1
+ OPENSSL_STATIC=1
+ generate_arch_flags arm64
+ '[' -z arm64 ']'
+ export TARGET_ARCH=arm64
+ TARGET_ARCH=arm64
+ download_and_setup_toolchain
++ uname
+ '[' Darwin == Darwin ']'
+ export TOOLCHAIN_PREFIX=/Users/ivan.pagac/android_build/toolchains/darwin
+ TOOLCHAIN_PREFIX=/Users/ivan.pagac/android_build/toolchains/darwin
+ mkdir -p /Users/ivan.pagac/android_build/toolchains/darwin
+ pushd /Users/ivan.pagac/android_build/toolchains/darwin
~/android_build/toolchains/darwin ~/Projects/aries-vcx
+ echo 'Resolving NDK for OSX'
Resolving NDK for OSX
+ download_and_unzip_if_missed android-ndk-r20 https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip
+ expected_directory=android-ndk-r20
+ url=https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip
++ date +%s
+ fname=tmp_1700485507_android-ndk-r20.zip
+ '[' '!' -d android-ndk-r20 ']'
+ echo 'Downloading https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip as tmp_1700485507_android-ndk-r20.zip'
Downloading https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip as tmp_1700485507_android-ndk-r20.zip
+ wget -q -O tmp_1700485507_android-ndk-r20.zip https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip
+ echo 'Unzipping tmp_1700485507_android-ndk-r20.zip'
Unzipping tmp_1700485507_android-ndk-r20.zip
+ unzip -qqo tmp_1700485507_android-ndk-r20.zip
+ rm tmp_1700485507_android-ndk-r20.zip
+ echo 'Done!'
Done!
+ popd
~/Projects/aries-vcx
+ export ANDROID_NDK_ROOT=/Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
+ ANDROID_NDK_ROOT=/Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
+ echo 'NDK RESOLVED AT /Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c'
NDK RESOLVED AT /Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
+ '[' arm64 == arm ']'
+ '[' arm64 == armv7 ']'
+ '[' arm64 == arm64 ']'
+ export TARGET_API=30
+ TARGET_API=30
+ export TRIPLET=aarch64-linux-android
+ TRIPLET=aarch64-linux-android
+ export ANDROID_TRIPLET=aarch64-linux-android
+ ANDROID_TRIPLET=aarch64-linux-android
+ export ABI=arm64-v8a
+ ABI=arm64-v8a
+ export TOOLCHAIN_SYSROOT_LIB=lib
+ TOOLCHAIN_SYSROOT_LIB=lib
+ '[' arm64 == x86 ']'
+ '[' arm64 == x86_64 ']'
+ export TOOLCHAIN_DIR=/Users/ivan.pagac/android_build/toolchains/darwin/arm64
+ TOOLCHAIN_DIR=/Users/ivan.pagac/android_build/toolchains/darwin/arm64
+ export PATH=/Users/ivan.pagac/android_build/toolchains/darwin/arm64/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools:/Users/ivan.pagac/android_build/sdk/tools/bin
+ PATH=/Users/ivan.pagac/android_build/toolchains/darwin/arm64/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/ivan.pagac/.rd/bin:/opt/homebrew/opt/node/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ivan.pagac/.cargo/bin:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/Library/Android/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/platform-tools:/Users/ivan.pagac/android_build/sdk/tools:/Users/ivan.pagac/android_build/sdk/tools/bin
+ echo 'SUCCESSFULLY PREPARED DEPS FOR arm64'
SUCCESSFULLY PREPARED DEPS FOR arm64
+ download_and_setup_toolchain
++ uname
+ '[' Darwin == Darwin ']'
+ export TOOLCHAIN_PREFIX=/Users/ivan.pagac/android_build/toolchains/darwin
+ TOOLCHAIN_PREFIX=/Users/ivan.pagac/android_build/toolchains/darwin
+ mkdir -p /Users/ivan.pagac/android_build/toolchains/darwin
+ pushd /Users/ivan.pagac/android_build/toolchains/darwin
~/android_build/toolchains/darwin ~/Projects/aries-vcx
+ echo 'Resolving NDK for OSX'
Resolving NDK for OSX
+ download_and_unzip_if_missed android-ndk-r20 https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip
+ expected_directory=android-ndk-r20
+ url=https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip
++ date +%s
+ fname=tmp_1700486125_android-ndk-r20.zip
+ '[' '!' -d android-ndk-r20 ']'
+ echo 'Skipping download https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip. Expected directory android-ndk-r20 was found'
Skipping download https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip. Expected directory android-ndk-r20 was found
+ popd
~/Projects/aries-vcx
+ export ANDROID_NDK_ROOT=/Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
+ ANDROID_NDK_ROOT=/Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
+ echo 'NDK RESOLVED AT /Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c'
NDK RESOLVED AT /Users/ivan.pagac/android_build/toolchains/darwin/android-ndk-r25c
```
